import type { Types } from "mongoose";
import { KnowledgeOutput, KnowledgeOutputSection, KnowledgeSession } from "../models/index.js";

type Tone = "primary" | "success" | "warning" | "danger";
type ChartKind = "bars" | "progress" | "donut" | "timeline";
interface SeedSection { key: string; title: string; description: string; notes: Array<{ title: string; description: string; meta?: string; status?: string }>; charts: Array<{ title: string; description?: string; kind: ChartKind; items: Array<{ label: string; value: number; detail?: string; tone?: Tone }> }> }
interface SessionSeed { title: string; subject: string; audience: string; opportunity: string; }

const workspaceSessions: Record<string, SessionSeed[]> = {
    "brand-ecommerce": [
        { title: "Brand Ecommerce Growth & Support", subject: "AI-assisted ecommerce support and conversion", audience: "online shoppers and customer-support operators", opportunity: "answer product and policy questions consistently while revealing purchase friction" },
        { title: "Brand Product Catalog Intelligence", subject: "searchable product catalog intelligence", audience: "merchandising, sales, and support teams", opportunity: "make catalog, availability, and product-comparison knowledge easier to discover" },
    ],
    vizr: [
        { title: "Vizr AI Agent Platform", subject: "a configurable AI agent platform", audience: "business owners, operators, and implementation teams", opportunity: "deploy governed agents from reusable knowledge, workflows, and channel integrations" },
        { title: "Vizr Omnichannel Operations", subject: "unified AI-assisted customer operations", audience: "support agents and channel managers", opportunity: "coordinate website, WhatsApp, Telegram, and email conversations in one operating model" },
    ],
};

const chart = (title: string, kind: ChartKind, items: Array<{ label: string; value: number; detail?: string; tone?: Tone }>, description?: string) => ({ title, kind, items, description });
const note = (title: string, description: string, status?: string, meta?: string) => ({ title, description, status, meta });

const planSections = (seed: SessionSeed): SeedSection[] => [
    { key: "idea", title: "Idea", description: `Create ${seed.subject} for ${seed.audience}. The central opportunity is to ${seed.opportunity}.`, notes: [note("Primary outcome", `Deliver a dependable experience for ${seed.audience}.`, "Strategic"), note("Value hypothesis", `The solution can help teams ${seed.opportunity}.`, "Validate"), note("Success definition", "Users receive useful results with visible evidence, safe fallback behavior, and measurable quality.", "Target")], charts: [chart("Value emphasis", "donut", [{ label: "Quality", value: 36 }, { label: "Experience", value: 27 }, { label: "Efficiency", value: 22 }, { label: "Insight", value: 15 }])] },
    { key: "requirements", title: "Requirements", description: "Capabilities and controls required to deliver the idea safely and operate it reliably.", notes: [note("Structured knowledge", "Approved content must have ownership, lifecycle status, and session-level isolation.", "Critical"), note("Grounded answers", "Retrieval and response policies must connect outputs to relevant source evidence.", "Critical"), note("Access control", "Workspace and user permissions must be enforced before data reaches an AI provider.", "Critical"), note("Observability", "Latency, usage, failures, quality, and content gaps must be measurable.", "High"), note("Human control", "Operators need clear escalation and override paths for uncertain cases.", "High")], charts: [chart("Requirement readiness", "bars", [{ label: "Knowledge", value: 82 }, { label: "Security", value: 74 }, { label: "Experience", value: 68 }, { label: "Analytics", value: 51 }, { label: "Operations", value: 44 }])] },
    { key: "warnings", title: "Warnings", description: "Risks that require explicit mitigation and ownership before production rollout.", notes: [note("Unsupported output", "Generated answers may exceed available evidence without validation and fallback rules.", "High", "Owner: AI lead"), note("Data exposure", "Incorrect access filtering can expose content across users or sessions.", "Critical", "Owner: Security"), note("Source quality", "Outdated or contradictory content can produce unreliable results.", "High", "Owner: Domain team"), note("Cost growth", "Large contexts and repeated generation can increase operating cost.", "Medium", "Owner: Platform")], charts: [chart("Risk exposure", "bars", [{ label: "Data access", value: 88, tone: "danger" }, { label: "Accuracy", value: 79, tone: "warning" }, { label: "Source quality", value: 67, tone: "warning" }, { label: "Cost", value: 43 }, { label: "Adoption", value: 35 }], "Severity × likelihood planning score")] },
    { key: "work-plan", title: "Work Plan", description: "A phased path from validation through controlled production adoption.", notes: [note("1. Discovery", "Confirm users, use cases, source owners, constraints, and acceptance criteria.", "Complete", "Week 1"), note("2. Knowledge preparation", "Audit, classify, normalize, and ingest approved high-value content.", "In progress", "Week 2"), note("3. Core implementation", "Deliver retrieval, generation, citations, permissions, and session workflows.", "Planned", "Weeks 3–4"), note("4. Validation", "Run quality, security, failure-path, and performance evaluations.", "Planned", "Week 5"), note("5. Pilot launch", "Release to a bounded audience and measure real usage outcomes.", "Planned", "Week 6"), note("6. Optimization", "Close content gaps and tune quality, cost, and latency.", "Planned", "Ongoing")], charts: [chart("Phase progress", "timeline", [{ label: "Discovery", value: 100, detail: "Week 1" }, { label: "Knowledge", value: 70, detail: "Week 2" }, { label: "Implementation", value: 30, detail: "Weeks 3–4" }, { label: "Validation", value: 0, detail: "Week 5" }, { label: "Pilot", value: 0, detail: "Week 6" }, { label: "Optimize", value: 0, detail: "Ongoing" }])] },
    { key: "implementation", title: "Implementation", description: "Concrete work packages with ownership, dependencies, effort, and deliverables.", notes: [note("Define the knowledge contract", "Specify ingestion states, metadata, deduplication, retries, and ownership.", "High", "Platform · 3 days"), note("Build scoped retrieval", "Retrieve and rank evidence within the active workspace and session only.", "Critical", "AI · 5 days"), note("Add response validation", "Enforce citation and fallback rules before returning generated content.", "Critical", "AI · 4 days"), note("Instrument outcomes", "Capture quality, latency, cost, feedback, and unanswered-question signals.", "High", "Full stack · 3 days"), note("Complete release review", "Require quality and security thresholds before broad availability.", "High", "QA + domain owner · 4 days")], charts: [chart("Estimated effort", "bars", [{ label: "AI and retrieval", value: 64, detail: "16 days" }, { label: "Backend", value: 48, detail: "12 days" }, { label: "Frontend", value: 36, detail: "9 days" }, { label: "Quality", value: 28, detail: "7 days" }, { label: "Operations", value: 20, detail: "5 days" }])] },
    { key: "expected-outcome", title: "Expected Outcome", description: `A production-ready foundation for ${seed.subject}, with controlled access, measurable quality, and a repeatable improvement cycle.`, notes: [note("Trusted experience", "Users receive clear results with visible evidence and honest uncertainty."), note("Operational control", "Owners can inspect usage, quality, gaps, latency, and cost."), note("Scalable foundation", "The structure can support additional sessions and use cases without UI changes.")], charts: [chart("Launch acceptance targets", "progress", [{ label: "Grounded result rate", value: 92, detail: "Target ≥ 90%" }, { label: "Citation coverage", value: 96, detail: "Target ≥ 95%" }, { label: "Critical security tests", value: 100, detail: "Required" }, { label: "Performance target", value: 84, detail: "P95 under 4s" }])] },
];

const reportSections = (seed: SessionSeed): SeedSection[] => [
    { key: "executive-summary", title: "Executive Summary", description: `The analysis finds a credible opportunity to use ${seed.subject} to ${seed.opportunity}. A controlled pilot is recommended before broad rollout.`, notes: [note("What was analyzed", `Business value, delivery readiness, and operating risk for ${seed.subject}.`), note("Recommendation", "Proceed with a bounded implementation supported by quality and security gates.", "Proceed"), note("Expected impact", "The approach can improve access, consistency, and operational insight without removing expert oversight.")], charts: [chart("Readiness overview", "progress", [{ label: "Knowledge", value: 82 }, { label: "Experience", value: 71 }, { label: "Security", value: 74 }, { label: "Operations", value: 52 }])] },
    { key: "current-situation", title: "Current Situation / Problem", description: `Today, ${seed.audience} face fragmented information, inconsistent responses, and limited visibility into recurring knowledge gaps.`, notes: [note("Fragmented discovery", "Relevant information is distributed across sources and systems.", "High"), note("Response variation", "Different operators can interpret the same source differently.", "Quality risk"), note("Hidden gaps", "Missing knowledge is usually discovered after an unsuccessful interaction.", "Operational risk"), note("Manual scaling", "Repeated information work grows with demand.", "Efficiency")], charts: [chart("Current friction", "bars", [{ label: "Search time", value: 78 }, { label: "Inconsistency", value: 66 }, { label: "Coverage gaps", value: 59 }, { label: "Manual repetition", value: 73 }])] },
    { key: "key-findings", title: "Key Findings", description: "The strongest findings connect source quality, evidence visibility, safe fallback behavior, and ongoing measurement.", notes: [note("Strong assistance potential", "Recurring informational work can potentially be handled from approved content.", "High impact"), note("Quality begins with sources", "Retrieval cannot correct stale or contradictory source material.", "Critical"), note("Evidence builds trust", "Citations allow users to verify results and identify source ownership.", "High impact"), note("Fallback prevents false confidence", "The system must decline when evidence is insufficient.", "Critical")], charts: [chart("Finding impact", "bars", [{ label: "Assistance", value: 87 }, { label: "Source quality", value: 94 }, { label: "Evidence", value: 82 }, { label: "Fallback", value: 91 }])] },
    { key: "benefits", title: "Benefits / Value", description: `The recommended approach can help ${seed.audience} access consistent information more quickly and turn interaction patterns into improvement priorities.`, notes: [note("Faster access", "Users can explore relevant knowledge conversationally."), note("Consistency", "Shared policies can reduce response variation."), note("Scalable support", "Repeated informational requests can be supported concurrently."), note("Knowledge insight", "Unanswered questions can identify content priorities."), note("Visible evidence", "Citations connect output to approved sources."), note("Availability", "Common knowledge can remain accessible beyond staffed hours.")], charts: [chart("Value contribution", "donut", [{ label: "Experience", value: 29 }, { label: "Efficiency", value: 27 }, { label: "Consistency", value: 24 }, { label: "Insight", value: 20 }])] },
    { key: "recommended-solution", title: "Recommended Solution & Architecture", description: "Use modular experience, application, knowledge, intelligence, and operations layers so capabilities can evolve independently.", notes: [note("Experience layer", "Session navigation, generated outputs, evidence, feedback, and fallback."), note("Application layer", "Authentication, permissions, orchestration, APIs, and budgets."), note("Knowledge layer", "Ingestion, metadata, retrieval, ranking, and isolation."), note("Intelligence layer", "Context assembly, generation, validation, and model routing."), note("Operations layer", "Evaluation, monitoring, analytics, audit, and alerts.")], charts: [chart("Component readiness", "progress", [{ label: "Experience", value: 71 }, { label: "Application", value: 77 }, { label: "Knowledge", value: 82 }, { label: "Intelligence", value: 64 }, { label: "Operations", value: 49 }])] },
    { key: "impact-analysis", title: "Impact Analysis", description: "Directional planning estimates show the strongest potential in scalability and efficiency; they are not guaranteed outcomes.", notes: [note("Efficiency", "May reduce time spent locating and repeating approved information."), note("Experience", "Can shorten response delays and simplify knowledge discovery."), note("Scalability", "Can support additional demand while preserving human attention for complex work."), note("Maintainability", "Source ownership and gap analytics can create a clearer improvement process.")], charts: [chart("Potential impact", "bars", [{ label: "Efficiency", value: 84 }, { label: "Experience", value: 79 }, { label: "Scalability", value: 88 }, { label: "Maintainability", value: 71 }, { label: "Security", value: 63 }])] },
    { key: "risks", title: "Risks & Challenges", description: "Production value depends on controlling answer accuracy, privacy, source quality, integration behavior, and cost.", notes: [note("Unsupported claims", "Generated content may exceed the available evidence.", "High", "Citations + fallback"), note("Privacy", "Content can be exposed without retrieval-time permissions.", "Critical", "Scoped authorization"), note("Knowledge quality", "Stale sources can create misleading results.", "High", "Ownership + review dates"), note("Integration complexity", "External systems may have inconsistent identity and availability.", "Medium", "Adapters + graceful failure"), note("Cost variability", "Usage and context length affect operating cost.", "Medium", "Budgets + routing")], charts: [chart("Residual risk", "bars", [{ label: "Accuracy", value: 46, tone: "warning" }, { label: "Privacy", value: 38, tone: "danger" }, { label: "Source quality", value: 43, tone: "warning" }, { label: "Integration", value: 31 }, { label: "Cost", value: 28 }], "Estimated after planned mitigation")] },
    { key: "recommendations", title: "Recommendations", description: "Prioritized actions to convert the analysis into a controlled delivery decision.", notes: [note("Assign source ownership", "Give each production source an owner, review date, and access policy.", "Critical"), note("Establish evaluation", "Test representative scenarios before and after material changes.", "High"), note("Require safe fallback", "Avoid definitive output when supporting evidence is unavailable.", "High"), note("Pilot with a bounded audience", "Expand only after quality targets are achieved.", "Medium"), note("Review gaps continuously", "Use unsuccessful requests to prioritize content improvements.", "Ongoing")], charts: [chart("Recommendation sequence", "timeline", [{ label: "Ownership", value: 100, detail: "Now" }, { label: "Evaluation", value: 90, detail: "Week 1" }, { label: "Fallback", value: 82, detail: "Week 2" }, { label: "Pilot", value: 61, detail: "Week 4" }, { label: "Optimize", value: 40, detail: "Ongoing" }])] },
    { key: "conclusion", title: "Conclusion", description: `${seed.subject} is a strong candidate for a controlled implementation. The next step is to approve requirements, assign source owners, and establish a measurable pilot rather than launch broadly without evidence.`, notes: [note("Decision", "Proceed with a controlled pilot.", "Recommended"), note("Why it matters", `The solution can help ${seed.audience} ${seed.opportunity}.`), note("Immediate next step", "Approve requirements and create the evaluation baseline.")], charts: [] },
];

const outputVariants = {
    plan: [
        { key: "implementation", label: "Implementation Plan", category: "Implementation plan" },
        { key: "launch", label: "Launch Plan", category: "Launch plan" },
        { key: "growth", label: "Growth Plan", category: "Growth plan" },
    ],
    report: [
        { key: "analysis", label: "Analysis Report", category: "AI analysis" },
        { key: "readiness", label: "Readiness Report", category: "Readiness analysis" },
        { key: "impact", label: "Impact Report", category: "Impact analysis" },
    ],
} as const;

const seedOutput = async (workspaceId: Types.ObjectId, ownerId: Types.ObjectId, sessionId: Types.ObjectId, kind: "plan" | "report", seed: SessionSeed, variant: { key: string; label: string; category: string }) => {
    const sections = kind === "plan" ? planSections(seed) : reportSections(seed);
    const output = await KnowledgeOutput.findOneAndUpdate(
        { workspaceId, sessionId, kind, seedKey: variant.key },
        { $set: { createdBy: ownerId, title: `${seed.title} ${variant.label}`, description: kind === "plan" ? `${variant.label} and execution roadmap for ${seed.subject}.` : `${variant.label} covering value, readiness, impact, and risk for ${seed.subject}.`, category: variant.category, status: "ready" }, $setOnInsert: { workspaceId, sessionId, kind, seedKey: variant.key, version: 1 } },
        { upsert: true, returnDocument: "after", runValidators: true },
    ).exec();
    if (!output) throw new Error(`Could not seed ${kind} for ${seed.title}.`);
    await Promise.all(sections.map((section, order) => KnowledgeOutputSection.findOneAndUpdate(
        { outputId: output._id, key: section.key },
        { $set: { workspaceId, sessionId, outputId: output._id, ...section, order, status: "ready", error: "" } },
        { upsert: true, returnDocument: "after", runValidators: true },
    ).exec()));
    return sections.length;
};

export const seedKnowledgeOutputs = async (workspaces: Array<{ _id: Types.ObjectId; ownerId: Types.ObjectId; slug: string }>) => {
    let sessionCount = 0;
    let outputCount = 0;
    let schemaCount = 0;
    try { await KnowledgeOutput.collection.dropIndex("workspaceId_1_sessionId_1_kind_1"); } catch (error: any) {
        if (error?.codeName !== "IndexNotFound" && error?.code !== 27) throw error;
    }
    await KnowledgeOutput.syncIndexes();
    for (const workspace of workspaces.filter((item) => workspaceSessions[item.slug])) {
        for (const seed of workspaceSessions[workspace.slug]) {
            const session = await KnowledgeSession.findOneAndUpdate(
                { workspaceId: workspace._id, title: seed.title },
                { $set: { createdBy: workspace.ownerId, status: "empty", sourceCount: 0, readySourceCount: 0, totalBytes: 0 }, $setOnInsert: { workspaceId: workspace._id, title: seed.title } },
                { upsert: true, returnDocument: "after", runValidators: true },
            ).exec();
            if (!session) throw new Error(`Could not seed knowledge session ${seed.title}.`);
            sessionCount += 1;
            for (const variant of outputVariants.plan) schemaCount += await seedOutput(workspace._id, workspace.ownerId, session._id, "plan", seed, variant);
            for (const variant of outputVariants.report) schemaCount += await seedOutput(workspace._id, workspace.ownerId, session._id, "report", seed, variant);
            outputCount += outputVariants.plan.length + outputVariants.report.length;
        }
    }
    return { sessions: sessionCount, outputs: outputCount, schemas: schemaCount };
};
