import type { Request, Response } from "express";
import { asyncHandler } from "../middlewares/asyncHandler.js";
import * as service from "../services/aiManagement.js";
const slug = (req: Request) => typeof req.query.system_slug === "string" ? req.query.system_slug : undefined;
const id = (req: Request) => String(req.params.id);
export const overview = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.getAIOverviewService(res.locals.user, slug(req)) }); });
export const providers = asyncHandler(async (_req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.listAIProvidersService() }); });
export const updateProvider = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.updateAIProviderService(id(req), req.body) }); });
export const models = asyncHandler(async (_req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.listAIModelsService() }); });
export const createModel = asyncHandler(async (req: Request, res: Response) => { res.status(201).json({ success: true, data: await service.saveAIModelService(req.body) }); });
export const updateModel = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.saveAIModelService(req.body, id(req)) }); });
export const deleteModel = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.deleteAIModelService(id(req)) }); });
export const agents = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.listAIAgentsService(res.locals.user, slug(req)) }); });
export const createAgent = asyncHandler(async (req: Request, res: Response) => { res.status(201).json({ success: true, data: await service.saveAIAgentService(res.locals.user, slug(req), req.body) }); });
export const updateAgent = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.saveAIAgentService(res.locals.user, slug(req), req.body, id(req)) }); });
export const deleteAgent = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.deleteAIAgentService(res.locals.user, slug(req), id(req)) }); });
export const logs = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.listAIRequestLogsService(res.locals.user, slug(req)) }); });
export const routing = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.listAIRoutingService(res.locals.user, slug(req)) }); });
export const quotas = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.listAIQuotasService(res.locals.user, slug(req)) }); });
export const createRouting = asyncHandler(async (req: Request, res: Response) => { res.status(201).json({ success: true, data: await service.saveAIRoutingService(res.locals.user, slug(req), req.body) }); });
export const updateRouting = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.saveAIRoutingService(res.locals.user, slug(req), req.body, id(req)) }); });
export const deleteRouting = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.deleteAIRoutingService(res.locals.user, slug(req), id(req)) }); });
export const createQuota = asyncHandler(async (req: Request, res: Response) => { res.status(201).json({ success: true, data: await service.saveAIQuotaService(res.locals.user, slug(req), req.body) }); });
export const updateQuota = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.saveAIQuotaService(res.locals.user, slug(req), req.body, id(req)) }); });
export const deleteQuota = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.deleteAIQuotaService(res.locals.user, slug(req), id(req)) }); });
export const analytics = asyncHandler(async (req: Request, res: Response) => { res.status(200).json({ success: true, data: await service.getAIAnalyticsService(res.locals.user, slug(req)) }); });
